run:
  timeout: 5m

linters-settings:
  lll:
    line-length: 140
  goimports:
    local-prefixes: backend

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - staticcheck
    - unused
  disable:
    - depguard
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: docs/
      linters:
        - all
